# Generated by Django 4.2.25 on 2025-10-29 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_atribuicao_colaborador_funcao_empresa_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('empresa', 'Empresas'), ('colaborador', 'Colaboradores'), ('veiculo', 'Veículos'), ('atribuicao', 'Atribuições')], max_length=20)),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ok', models.BooleanField(default=False)),
                ('total_processado', models.IntegerField(default=0)),
                ('total_erros', models.IntegerField(default=0)),
                ('log', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=100)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('LIBERADO', 'Liberado'), ('BLOQUEADO', 'Bloqueado'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colaborador')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.veiculo')),
            ],
        ),
    ]
